# 0.1 Introduction to Numpy

As with any other package we start off by importing the library, NumPy in this case, by its most commonly used alias, np.

In [1]:
import numpy as np

#### Create a 1-dimensional array

In [3]:
a = np.array([1,4,2,3,5,7,8,6])
a

array([1, 4, 2, 3, 5, 7, 8, 6])

#### Create a 2-dimensional array

In [4]:
b = np.array([[5,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
b

array([[5, 0, 1, 0, 2, 3],
       [1, 3, 0, 1, 2, 0],
       [0, 1, 0, 0, 1, 3]])

Alternatively, we can initialize an array by calling on common functions like zeros, ones, full, and random. The first argument to all these functions is the shape of the array we would like. 

#### Create a 2x2 array of all zeros

In [7]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

#### Create an 1x2 array of all ones

In [8]:
np.ones((1, 2))

array([[1., 1.]])

#### Create a 2x2 constant array of the number 7

In [9]:
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

#### Creates a 2x2 array filled with random values between 0 and 1

In [10]:
np.random.seed(42) # set a seed to that we always get the same random values
c = np.random.random((2, 2))
c

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848]])

#### Create a 2x2 identity matrix

In [11]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

Once we have some data as a NumPy array, it is useful to observe its defining features. Here are a few:

#### Shape and size

In [14]:
print(a.shape)
print(b.shape)

(8,)
(3, 6)


Find the number of dimensions (ndim) of an array 

In [16]:
print('Number of dimensions of NumPy array "a"')
print(a.ndim)
print('Number of dimensions of NumPy array "b"')
print(b.ndim)

Number of dimensions of NumPy array "a"
1
Number of dimensions of NumPy array "b"
2


Total number of elements (size) of an array 

In [17]:
print('Total number of elements in NumPy array "a"')
print(a.size)

print('Total number of elements in NumPy array "b"')
print(b.size)

print('Total number of elements in NumPy array "c"')
print(c.size)

Total number of elements in NumPy array "a"
8
Total number of elements in NumPy array "b"
18
Total number of elements in NumPy array "c"
4


## DataType

In [19]:
print('Type of data stored in NumPy array "a"')
print(a.dtype.name)

print('Type of data stored in NumPy array "b"')
print(b.dtype.name)

print('Type of data stored in NumPy array "c"')
print(c.dtype.name)

Type of data stored in NumPy array "a"
int32
Type of data stored in NumPy array "b"
int32
Type of data stored in NumPy array "c"
float64


dtype tells us the type of each element stored in the array. When the array has integers, the type is 'int64', i.e. 64-bit integers. When the array has real numbers, the type is 'float64', i.e. 64-bit floating point values.

#### Size of an individual array element (in bytes)

In [20]:
print('Size of an individual array elements in NumPy array "a"')
print(a.itemsize)
print()

print('Size of an individual array elements in NumPy array "b"')
print(b.itemsize)
print()

print('Size of an individual array elements in NumPy array "c"')
print(c.itemsize)

Size of an individual array elements in NumPy array "a"
4

Size of an individual array elements in NumPy array "b"
4

Size of an individual array elements in NumPy array "c"
8


Since 8 bits = 1 byte, and we have 64-bit integers and floats, the number of bytes per array element is 64 / 8 = 8. 

#### The type of array itself

In [21]:
print(type(a))

<class 'numpy.ndarray'>


####  using attributes to create new arrays

In [23]:
# Create an array of zeroes of the same shape as "b"
print('A new array of zeroes of the same shape as "b"')
print(np.zeros(b.shape))
print()

# Create an array of ones of the same shape as "a"
print('A new array of ones of the same shape as "a"')
print(np.ones(a.shape))

A new array of zeroes of the same shape as "b"
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

A new array of ones of the same shape as "a"
[1. 1. 1. 1. 1. 1. 1. 1.]


## indexing

In [24]:
# Recall what array a looked like
print('array "a"')
print(a)
print()

# Indexing. As always, indexes start from 0.
print('First element of array "a"')
print(a[0])   # element 1
print()

print('Second element of array "a"')
print(a[1])   # element 2

array "a"
[1 4 2 3 5 7 8 6]

First element of array "a"
1

Second element of array "a"
4


For 2-dimensional arrays, we use the notation array[i, j] to pull out the element in row i, column j.

In [25]:
# Recall what array b looked like
print('array "b"')
print(b)
print()

# Indexing. As always, indexes start from 0.
print('Element from row 0, column 1, of array "b"')
print(b[0, 1])   # (row 0, column 1)

array "b"
[[5 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]

Element from row 0, column 1, of array "b"
0


Note: This syntax is different from having a list of lists in Python. In that case, you would do a[i][j] (as opposed to a[i, j]).

## slicing

Instead of just a single element, it is also possible for us to look at sub-arrays or sub-parts of the original array. This is done using slicing. 

In [26]:
# Slicing pulls out a subarray
# Example for pulling out elements 2 through 4
# (element 2 is included and 4 is not, same as python list slicing).
print('Elements 2 through 4 (4 not included), of array "a"')
print(a[2:4])
print()

# Example for pulling out first 3 elements
print('First 3 elements of array "a"')
print(a[:3])

Elements 2 through 4 (4 not included), of array "a"
[2 3]

First 3 elements of array "a"
[1 4 2]


#### Similar to indexing, slicing can be done on higher dimensional arrays as well.

In [27]:
# Example for pulling out first 2 rows and columns 1 though 3
# (column 1 is included and 3 is not, same as python list slicing).
print('First 2 rows and columns 1 through 3 (3 not included) of array "b" ')
print(b[:2, 1:3])
print()

# Values from row 1 through 2 and all columns
print('Values from row 1 through 2 and all columns, of array "b"')
print(b[1:2, :])
print()

# Values from all rows and column 2
print('Values from all rows and column 2')
print(b[:, 2])

First 2 rows and columns 1 through 3 (3 not included) of array "b" 
[[0 1]
 [3 0]]

Values from row 1 through 2 and all columns, of array "b"
[[1 3 0 1 2 0]]

Values from all rows and column 2
[1 0 0]


Note that there is a small but important difference in the last two examples. b[1:2,:] returns a 2-D array of shape (1, 6). Whereas b[:,2] returns a 1-D array of shape (3, ). 

#### modifying elements

In [29]:
b[0, 0] = 7  # sets the first value in the first column to 7.
print(b)

[[7 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]


In [30]:
d = np.copy(b)
d[1:3, 2:4] = 9  # sets all values in the subarray to 9.
print(d)

[[7 0 1 0 2 3]
 [1 3 9 9 2 0]
 [0 1 9 9 1 3]]


We can also set each element in a sub-array to different values, as defined by another array. This array must have the same shape as the sub-array we select.

In [31]:
d[:2, 1:3] = np.array([[2, 0], [4, 3]])
print(d)

[[7 2 0 0 2 3]
 [1 4 3 9 2 0]
 [0 1 9 9 1 3]]


#### Conditionals and Conditional Indexing

In [32]:
# Recall what array a looked like
print('array "a"')
print(a)
print()

print('Conditional of array "a", for elements of "a" greater than 2')
print(a > 2)

array "a"
[1 4 2 3 5 7 8 6]

Conditional of array "a", for elements of "a" greater than 2
[False  True False  True  True  True  True  True]


This array of True and False can be used for indexing.

In [33]:
print('Values of array "a" larger than 2')
print(a[a > 2]) # values of a larger than 2

Values of array "a" larger than 2
[4 3 5 7 8 6]


In [34]:
# Recall what array b looked like
print('array "b"')
print(b)
print()

print('Conditional of array "b", for elements of "b" greater than 2')
print(b > 2)
print()

print('Values of array "b" larger than 2')
print(b[b > 2])

array "b"
[[7 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]

Conditional of array "b", for elements of "b" greater than 2
[[ True False False False False  True]
 [False  True False False False False]
 [False False False False False  True]]

Values of array "b" larger than 2
[7 3 3 3]


Note above that when we performed conditional indexing on a 2-D array, the result was a flattened array. This is true when the conditional (in this case, b > 2) has the same shape as the original array (in this case, b).

NumPy doesn't have a choice here but to flatten the result, since it is possible for the result to include different number of values from each row and column. In the example above, 2 values in row 1 are greater than 2, but only 1 value from rows 2 and 3 are greater than 2.

#### Conclusion

In summary, advantages of using NumPy

    array oriented computing
    efficiently implemented multi-dimensional arrays
    designed for scientific computation
    sophisticated functions for initializing, indexing and slicing

# 0.2 Numpy Operations

Let's start by defining some arrays 

In [1]:
import numpy as np

# Create a 1-dimensional array
a = np.array([1,4,2,3,5,7,8,6])
print('array "a"')
print(a)
print()

# Create a 2-dimensional array
b = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
print('array "b"')
print(b)

array "a"
[1 4 2 3 5 7 8 6]

array "b"
[[1 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]


#### Element-wise operations (add, multiply, etc)

In [2]:
c = b + 5
print(c)

[[6 5 6 5 7 8]
 [6 8 5 6 7 5]
 [5 6 5 5 6 8]]


In [3]:
# Element-wise addition
print('Element-wise sum of "b" and "c"')
print(b + c)
print()

print('Element-wise sum of "b" and "c"')
print(np.add(b, c))

Element-wise sum of "b" and "c"
[[ 7  5  7  5  9 11]
 [ 7 11  5  7  9  5]
 [ 5  7  5  5  7 11]]

Element-wise sum of "b" and "c"
[[ 7  5  7  5  9 11]
 [ 7 11  5  7  9  5]
 [ 5  7  5  5  7 11]]


In [4]:
# Element-wise subtraction
print('Element-wise difference of "b" and "c"')
print(b - c)
print()

print('Element-wise difference of "b" and "c"')
print(np.subtract(b, c))

Element-wise difference of "b" and "c"
[[-5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5]]

Element-wise difference of "b" and "c"
[[-5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5]]


In [5]:
# Element-wise multiplication
print('Element-wise multiplication of "b" and "c"')
print(b * c)
print()

print('Element-wise multiplication of "b" and "c"')
print(np.multiply(b, c))

Element-wise multiplication of "b" and "c"
[[ 6  0  6  0 14 24]
 [ 6 24  0  6 14  0]
 [ 0  6  0  0  6 24]]

Element-wise multiplication of "b" and "c"
[[ 6  0  6  0 14 24]
 [ 6 24  0  6 14  0]
 [ 0  6  0  0  6 24]]


In [6]:
# Element-wise division
print('Element-wise division of "b" and "c" ')
print(b / c)

Element-wise division of "b" and "c" 
[[0.16666667 0.         0.16666667 0.         0.28571429 0.375     ]
 [0.16666667 0.375      0.         0.16666667 0.28571429 0.        ]
 [0.         0.16666667 0.         0.         0.16666667 0.375     ]]


Note: The arrays are implicitly converted to float in latest NumPy versions.

In [7]:
# Element-wise square-root
print('Element-wise square root of array "b"')
print(np.sqrt(b))

Element-wise square root of array "b"
[[1.         0.         1.         0.         1.41421356 1.73205081]
 [1.         1.73205081 0.         1.         1.41421356 0.        ]
 [0.         1.         0.         0.         1.         1.73205081]]


#### Aggregation operations (sum, min, max, etc)

In [8]:
# Sum of all elements
print('Sum of all elements of array "b"')
print(b.sum())
print()

# Sum of each column
print('Sum of each column of array "b"')
print(b.sum(axis=0))
print()

# Sum of each row
print('Sum of each row of array "b"')
print(b.sum(axis=1))

Sum of all elements of array "b"
19

Sum of each column of array "b"
[2 4 1 1 5 6]

Sum of each row of array "b"
[7 7 5]


In [9]:
# Minimum of all values
print('Minimum of all values of array "b"')
print(b.min())
print()

# Maximum across axis 1
print('Maximum across axis 1 of array "b"')
print(b.max(axis=1))
print()

# Cumulative sum across axis 0
print('Cumulative sum across axis 0 of array "b"')
print(b.cumsum(axis=0))

Minimum of all values of array "b"
0

Maximum across axis 1 of array "b"
[3 3 3]

Cumulative sum across axis 0 of array "b"
[[1 0 1 0 2 3]
 [2 3 1 1 4 3]
 [2 4 1 1 5 6]]


###### And also mean, median, std (standard deviation).

In [12]:
print('Mean along axis 0 of array "b"')
print(b.mean(axis=0))
print()

print('Median along axis 0 of array "b"')
print(np.median(b, axis=0))
print()

print('Standard deviation along axis 0 of array "b"')
print(np.std(b, axis=0))
print()

print('Mean along axis 0 of array "b"')
print(np.mean(b, axis=0))

Mean along axis 0 of array "b"
[0.66666667 1.33333333 0.33333333 0.33333333 1.66666667 2.        ]

Median along axis 0 of array "b"
[1. 1. 0. 0. 2. 3.]

Standard deviation along axis 0 of array "b"
[0.47140452 1.24721913 0.47140452 0.47140452 0.47140452 1.41421356]

Mean along axis 0 of array "b"
[0.66666667 1.33333333 0.33333333 0.33333333 1.66666667 2.        ]


In [13]:
print('unique elements in array "b"')
print(np.unique(b))

unique elements in array "b"
[0 1 2 3]


#### Matrix Operations (dot products, matrix multiplication, etc)

In [15]:
# Create array "v"
v = b[:, 0]
print('array "v"')
print(v)
print()

# Create array "w"
w = b[:, 1]
print('array "w"')
print(w)

array "v"
[1 1 0]

array "w"
[0 3 1]


##### Dot Product

In [16]:
# Inner product of vectors: v[0]*w[0] + v[1]*w[1] + ... v[n]*w[n]
print('Dot product of "v" and "w"')
print(v.dot(w)) # or np.dot(v, w)
print()

print('Dot product of "v" and "v"')
print(v.dot(v)) # or np.dot(v, v)

Dot product of "v" and "w"
3

Dot product of "v" and "v"
2


When the arrays are 2-dimensional, dot-product is equivalent to performing matrix multiplication. Below are examples of matrix-vector multiplication and matrix-matrix multiplication. 

In [17]:
# Transpose of a matrix
print('Transpose of "b"')
print(b.T)
print()

# Matrix-vector product
print('Matrix-vector product of "b-transpose" and "v"')
print(np.dot(b.T, v))
print()

# Matrix-matrix product (matrix multiplication)
print('Matrix-matrix product of "b-transpose" and "b"')
print(np.dot(b.T, b))

Transpose of "b"
[[1 1 0]
 [0 3 1]
 [1 0 0]
 [0 1 0]
 [2 2 1]
 [3 0 3]]

Matrix-vector product of "b-transpose" and "v"
[2 3 1 1 4 3]

Matrix-matrix product of "b-transpose" and "b"
[[ 2  3  1  1  4  3]
 [ 3 10  0  3  7  3]
 [ 1  0  1  0  2  3]
 [ 1  3  0  1  2  0]
 [ 4  7  2  2  9  9]
 [ 3  3  3  0  9 18]]


For dot products and matrix multiplication to be performed, the dimensions of the arrays need to be compatible. If they are not, NumPy will raise an exception.

In [18]:
# Incompatible dimensions (matrix-vector)
print(np.dot(b, v))

ValueError: shapes (3,6) and (3,) not aligned: 6 (dim 1) != 3 (dim 0)

In [19]:
# Incompatible dimensions (matrix-matrix)
print(np.dot(b, c))

ValueError: shapes (3,6) and (3,6) not aligned: 6 (dim 1) != 3 (dim 0)

#### sorting

In [20]:
print('array "a"')
print(a)
print()

# sort array "a"
print('sorted array "a"')
print(np.sort(a))

array "a"
[1 4 2 3 5 7 8 6]

sorted array "a"
[1 2 3 4 5 6 7 8]


The sort() function also accepts an axis parameter.

axis parameter is used to specify the axis along which we want to sort. In NumPy, axis values increase from the outside-in. For example, if we pass a 2D array and axis is 0, NumPy will sort each column. If axis is 1, NumPy will sort each row.

axis = -1 sorts along the last axis. This is also the default value. axis can also be None, in which case, the array is flattened and then the elements are sorted. 

In [21]:
print('array "b"')
print(b)
print()

# sort array "b" along rows, axis 1
print('array "b" sorted along rows (axis=1)')
print(np.sort(b, axis=1))
print()

# sort array "b" along rows (also the last axis in this case)
print('array "b" sorted along rows (axis=-1)')
print(np.sort(b, axis=-1))
print()

# sort array "b" along columns, axis 0
print('array "b" sorted along columns (axis=0)')
print(np.sort(b, axis=0))
print()

# sort array "b" after flattening it
print('array "b" flattened and then sorted (axis=None)')
print(np.sort(b, axis=None))

array "b"
[[1 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]

array "b" sorted along rows (axis=1)
[[0 0 1 1 2 3]
 [0 0 1 1 2 3]
 [0 0 0 1 1 3]]

array "b" sorted along rows (axis=-1)
[[0 0 1 1 2 3]
 [0 0 1 1 2 3]
 [0 0 0 1 1 3]]

array "b" sorted along columns (axis=0)
[[0 0 0 0 1 0]
 [1 1 0 0 2 3]
 [1 3 1 1 2 3]]

array "b" flattened and then sorted (axis=None)
[0 0 0 0 0 0 0 1 1 1 1 1 1 2 2 3 3 3]


In [22]:
# create a new array with 'nan' values
z = np.array([0, np.nan, 1, 2, np.nan, 7, 3, 5, 1, np.nan])
print('array with "nan" values')
print(z)
print()

# sort array and display
print('sorted array')
print(np.sort(z))

array with "nan" values
[ 0. nan  1.  2. nan  7.  3.  5.  1. nan]

sorted array
[ 0.  1.  1.  2.  3.  5.  7. nan nan nan]


to sort every column of array b inplace, we do:

In [23]:
b.sort(axis=0)
print(b)

[[0 0 0 0 1 0]
 [1 1 0 0 2 3]
 [1 3 1 1 2 3]]


#### summary

    perform element-wise operations like addition, subtraction, etc. and functions like square root, log, etc.
    performing aggregation operations like sum, cumulative sum, mean, etc
    performing dot products and matrix multiplications
    sorting numpy arrays

# 0.3 Manipulating arrays

Let's start by defining some arrays 

In [25]:
import numpy as np

# Create a 1-dimensional array
a = np.array([1,4,2,3,5,7,8,6])
print('array "a"')
print(a)
print()

# Create a 2-dimensional array
b = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
print('array "b"')
print(b)
print()

np.random.seed(42) # set a seed to that we always get the same random values
c = b + 5
print('array "c"')
print(c)

array "a"
[1 4 2 3 5 7 8 6]

array "b"
[[1 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]

array "c"
[[6 5 6 5 7 8]
 [6 8 5 6 7 5]
 [5 6 5 5 6 8]]


#### Reshape and flatten

In [26]:
# Reshape to shape 4 x 2
a = a.reshape(4, 2)
print('array "a" reshaped to 4 x 2')
print(a)
print()

# Reshape to shape 2 x 4
a = a.reshape(2, 4)
print('array "a" reshaped to 2 x 4')
print(a)

array "a" reshaped to 4 x 2
[[1 4]
 [2 3]
 [5 7]
 [8 6]]

array "a" reshaped to 2 x 4
[[1 4 2 3]
 [5 7 8 6]]


As you can see above, during reshaping to a 2-D object, values are filled row by row.

"Flatten" is equivalent to reshaping to vector of length a.size.

In [27]:
a = a.flatten()
print('Flattened array "a"')
print(a)

Flattened array "a"
[1 4 2 3 5 7 8 6]


#### Resize

If we would like to reshape while changing the total number of elements in the array, we can use resize. Resize will repeat elements (if resizing to a larger size), or it will throw away elements (if resizing to a smaller size).

In [28]:
print(np.resize(a, (3, 5)))

[[1 4 2 3 5]
 [7 8 6 1 4]
 [2 3 5 7 8]]


#### broadcasting

Broadcasting makes copies of the existing array.

The first argument is the array itself, and the second argument is the shape of the new array.

Since broadcasting makes copies of the original array, the trailing dimensions of the new array must match the dimensions of the original array. For example, we can broadcast an array of shape (8, ) to an array of shape (6, 8). But we cannot broadcast it to shape (6, 4). 

In [32]:
print('Broadcasting array "a" to a new size')
print(np.broadcast_to(a, (6, 8)))

Broadcasting array "a" to a new size
[[1 4 2 3 5 7 8 6]
 [1 4 2 3 5 7 8 6]
 [1 4 2 3 5 7 8 6]
 [1 4 2 3 5 7 8 6]
 [1 4 2 3 5 7 8 6]
 [1 4 2 3 5 7 8 6]]


Let's try broadcasting the 2D array. The original shape of B was (3, 6), and we will broadcast it to the shape (2, 3, 6). This will repeat the array twice.

In [33]:
print(b)
print()

print('Broadcasting array "b" to a new size')
z = np.broadcast_to(b, (2, 3, 6))
print('New shape', z.shape)
print(z)

[[1 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]

Broadcasting array "b" to a new size
New shape (2, 3, 6)
[[[1 0 1 0 2 3]
  [1 3 0 1 2 0]
  [0 1 0 0 1 3]]

 [[1 0 1 0 2 3]
  [1 3 0 1 2 0]
  [0 1 0 0 1 3]]]


#### Expanding and squeezing dimensions

expand_dims and squeeze can be used to add or remove dimensions from an array.

In [40]:
# Expand the shape of an array by inserting axis
z = np.expand_dims(b, axis=1) # expand at position 1
print('Expanded array "z"')
print('Shape of z', z.shape)
print(z)
print()

# Remove single-dimensional entries from the shape of an array
print('Squeezed array "z"')
print(np.squeeze(z))

Expanded array "z"
Shape of z (3, 1, 6)
[[[1 0 1 0 2 3]]

 [[1 3 0 1 2 0]]

 [[0 1 0 0 1 3]]]

Squeezed array "z"
[[1 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]


#### Concatenating and stacking

In [41]:
print('array "b"')
print(b)
print()

print('array "c"')
print(c)

array "b"
[[1 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]

array "c"
[[6 5 6 5 7 8]
 [6 8 5 6 7 5]
 [5 6 5 5 6 8]]


In [42]:
# Join arrays along an existing axis, axis 0
print('Concatenated array "b" and "c", along axis 0')
print(np.concatenate((b, c), axis=0))
print()

# Join arrays along an existing axis, axis 1
print('Concatenated arrays "b" and "c" along axis 1')
print(np.concatenate((b, c), axis=1))

Concatenated array "b" and "c", along axis 0
[[1 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]
 [6 5 6 5 7 8]
 [6 8 5 6 7 5]
 [5 6 5 5 6 8]]

Concatenated arrays "b" and "c" along axis 1
[[1 0 1 0 2 3 6 5 6 5 7 8]
 [1 3 0 1 2 0 6 8 5 6 7 5]
 [0 1 0 0 1 3 5 6 5 5 6 8]]


Unlike concatenation, stacking creates a new dimension:

In [43]:
# Join arrays along a new axis, 0
print('Stack arrays "b" and "c" along a new axis, 0')
z = np.stack((b, c), 0)
print(z.shape)
print(z)
print()

# Join arrays along a new axis, 1
print('Stack arrays "b" and "c" along a new axis, 1')
z = np.stack((b, c), 1)
print(z.shape)
print(z)

Stack arrays "b" and "c" along a new axis, 0
(2, 3, 6)
[[[1 0 1 0 2 3]
  [1 3 0 1 2 0]
  [0 1 0 0 1 3]]

 [[6 5 6 5 7 8]
  [6 8 5 6 7 5]
  [5 6 5 5 6 8]]]

Stack arrays "b" and "c" along a new axis, 1
(3, 2, 6)
[[[1 0 1 0 2 3]
  [6 5 6 5 7 8]]

 [[1 3 0 1 2 0]
  [6 8 5 6 7 5]]

 [[0 1 0 0 1 3]
  [5 6 5 5 6 8]]]


#### Splitting

split, hsplit (horizontal split) and vsplit (vertical split) can be used to split an array into equal-sized subarrays.

In [45]:
print('array "b"')
print(b)
print()

print('array "c"')
print(c)

array "b"
[[1 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]

array "c"
[[6 5 6 5 7 8]
 [6 8 5 6 7 5]
 [5 6 5 5 6 8]]


By default, split splits by the axis 0. For 2D arrays, this means splitting vertically:

In [46]:
print('Split array "b"')
print(np.split(b, 3))
print()

print('Split array "c"')
print(np.split(c, 3))

Split array "b"
[array([[1, 0, 1, 0, 2, 3]]), array([[1, 3, 0, 1, 2, 0]]), array([[0, 1, 0, 0, 1, 3]])]

Split array "c"
[array([[6, 5, 6, 5, 7, 8]]), array([[6, 8, 5, 6, 7, 5]]), array([[5, 6, 5, 5, 6, 8]])]


Now, let's look at some ways to split horizontally:

In [47]:
print('Split array "c" into 3 parts along axis 1')
print(np.split(c, 3, axis=1))
print()

print('Horizontally split array "b" into 2 parts')
print(np.hsplit(b, 2))
print()

print('Horizontally split array "b" into 3 parts')
print(np.hsplit(b, 3))

Split array "c" into 3 parts along axis 1
[array([[6, 5],
       [6, 8],
       [5, 6]]), array([[6, 5],
       [5, 6],
       [5, 5]]), array([[7, 8],
       [7, 5],
       [6, 8]])]

Horizontally split array "b" into 2 parts
[array([[1, 0, 1],
       [1, 3, 0],
       [0, 1, 0]]), array([[0, 2, 3],
       [1, 2, 0],
       [0, 1, 3]])]

Horizontally split array "b" into 3 parts
[array([[1, 0],
       [1, 3],
       [0, 1]]), array([[1, 0],
       [0, 1],
       [0, 0]]), array([[2, 3],
       [2, 0],
       [1, 3]])]


#### Append, insert and delete

In [48]:
print('array "a"')
print(a)
print()

# Append values to the end of an array
print('Values appended to array "a"')
print(np.append(a, [1, 2]))
print()

# Insert values (0, 0) along the given axis (0) at the given index (3)
print('Values inserted to array "a"')
print(np.insert(a, 3, [0, 0], axis=0))
print()

# Delete the element at given locations (1) along an axis (0)
print('Values deleted from array "a"')
print(np.delete(a, [1, 3], axis=0))

array "a"
[1 4 2 3 5 7 8 6]

Values appended to array "a"
[1 4 2 3 5 7 8 6 1 2]

Values inserted to array "a"
[1 4 2 0 0 3 5 7 8 6]

Values deleted from array "a"
[1 2 5 7 8 6]


Let's see some examples with 2D arrays:

In [49]:
# 2d array "b"
print('array "b"')
print(b)
print()

# Append row of values to the end of a 2darray
# Notice that the argument itself is a 2D array.
print('Values appended to array "b" along axis 0')
print(np.append(b, [[1, 2, 3, 4, 5, 6]], axis=0))
print()

# Append column of values to the end of a 2darray
print('Values appended to array "b" along axis 1')
print(np.append(b, [[7], [8], [9]], axis=1))
print()

# Insert values (5, 5, 5) along the given axis (1) at the given index (2)
print('Scalar values inserted to array "b" in column position 2')
print(np.insert(b, 2, 5, axis=1))
print()

# Insert values (1, 2, 3) along the given axis (1) at the given index (1)
print('Column vector inserted to array "b" in column position 1')
print(np.insert(b, [1], [[1],[2],[3]], axis=1))
print()

# Delete the row/column/array at given locations (1) along an axis (0)
print('Row deleted from array "b"')
print(np.delete(b, 1, axis=0))
print()

# Delete the row/column/array at given locations (2) along an axis (1)
print('Column deleted from array "b"')
print(np.delete(b, 2, axis=1))

array "b"
[[1 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]

Values appended to array "b" along axis 0
[[1 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]
 [1 2 3 4 5 6]]

Values appended to array "b" along axis 1
[[1 0 1 0 2 3 7]
 [1 3 0 1 2 0 8]
 [0 1 0 0 1 3 9]]

Scalar values inserted to array "b" in column position 2
[[1 0 5 1 0 2 3]
 [1 3 5 0 1 2 0]
 [0 1 5 0 0 1 3]]

Column vector inserted to array "b" in column position 1
[[1 1 0 1 0 2 3]
 [1 2 3 0 1 2 0]
 [0 3 1 0 0 1 3]]

Row deleted from array "b"
[[1 0 1 0 2 3]
 [0 1 0 0 1 3]]

Column deleted from array "b"
[[1 0 0 2 3]
 [1 3 1 2 0]
 [0 1 0 1 3]]


#### summary

    change the shape of a NumPy array using reshape and flatten
    change the size of a NumPy array using resize and broadcast_to
    join arrays using concatenate and stack
    split arrays using split
    append, insert and delete items / subarrays from an array