# 0.1 Pandas Introduction : Dataframes

We will need the Pandas and NumPy libraries for this tutorial, so let us load them at the beginning. 

In [1]:
import pandas as pd
import numpy as np

let's use the Pandas read_csv() function to read the dataset. 

In [2]:
adult_income = pd.read_csv("data/adult_income_data_small.csv")

#### Dataframes

The read_csv() function returns a DataFrame. A DataFrame is a 2-dimensional data structure — analogous to a spreadsheet or SQL table. It is generally the most commonly used Pandas object.

Once the data is loaded into a pandas DataFrame, the first step is to see how large the dataset is. For this, we can check the shape of the DataFrame, which tells us the number of rows (observations) and columns (variables).

In [5]:
print('Shape of dataset:', adult_income.shape)

Shape of dataset: (326, 6)


To get the column names, use the columns attribute:

In [6]:
print(adult_income.columns)

Index(['education', 'edu_yrs', 'sex', 'capital_gain', 'hours_per_week',
       'income'],
      dtype='object')


To get a glimpse of the data itself, we can see the first five rows using the head() method:

In [7]:
print(adult_income.head())

      education  edu_yrs     sex  capital_gain  hours_per_week income
0  Some-college       10    Male             0              40  <=50K
1  Some-college       10    Male             0              45  <=50K
2       HS-grad        9    Male             0              50   >50K
3       HS-grad        9  Female             0              50  <=50K
4     Doctorate       16    Male             0              40   >50K


In [8]:
print(adult_income.head(8))

      education  edu_yrs     sex  capital_gain  hours_per_week income
0  Some-college       10    Male             0              40  <=50K
1  Some-college       10    Male             0              45  <=50K
2       HS-grad        9    Male             0              50   >50K
3       HS-grad        9  Female             0              50  <=50K
4     Doctorate       16    Male             0              40   >50K
5       HS-grad        9    Male             0              20  <=50K
6          11th        7    Male             0              40  <=50K
7       HS-grad        9    Male             0              20  <=50K


#### Brief description of the Dataset

The features/variables in the dataset are described below:

    education: highest educational qualification (categorical)
    edu_yrs: total number of years spent in educational institutes (numerical)
    sex: Male or Female (categorical, binary)
    capital_gain: profits made through capital markets (numerical)
    hours_per_week: working hours per week (numerical)
    income: the target variable - either >50k or <=50K (categorical, binary)

#### Dataset overview

We can use the .info() method to look at the datatype of every variable, along with number of observations present, like so:

In [9]:
adult_income.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326 entries, 0 to 325
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   education       326 non-null    object
 1   edu_yrs         326 non-null    int64 
 2   sex             326 non-null    object
 3   capital_gain    326 non-null    int64 
 4   hours_per_week  326 non-null    int64 
 5   income          326 non-null    object
dtypes: int64(3), object(3)
memory usage: 15.4+ KB


As you can see, the numerical variables such as edu_yrs, capital_gain, etc have type int64 (64-bit integers), and the strings (categorical variables) such as education, sex, etc have type object. 

Finally, there's the .describe() method, which by default summarizes the numerical variables. For each numerical variable, it tells us the minimum value, maximum value, mean, standard deviation, etc. Even the 25th and 75th percentile values are included.

In [10]:
print(adult_income.describe())

          edu_yrs  capital_gain  hours_per_week
count  326.000000    326.000000      326.000000
mean     9.944785   1395.217791       40.263804
std      2.641099   8187.038408       12.982984
min      2.000000      0.000000        4.000000
25%      9.000000      0.000000       38.250000
50%     10.000000      0.000000       40.000000
75%     12.750000      0.000000       45.000000
max     16.000000  99999.000000       99.000000


The .describe() method also accepts an argument which allows us to specify which datatype we want a summary of. For categorical variables, the datatype is 'object'.

Hence, to get a summary, of the categorical variables, we will pass the parameter include with argument 'object'. When summarizing categorical variables, the .describe() method includes information about the number of unique values for the variable, the most common value for the variable, etc. 

In [11]:
print(adult_income.describe(include='object'))

       education   sex income
count        326   326    326
unique        15     2      2
top      HS-grad  Male  <=50K
freq         102   215    235


#### Sorting a DataFrame - sort_values()

Sometimes in order to do data exploration or feature engineering, we might need the DataFrame to be sorted in a particular order.

For example, suppose we want the adult-income dataset to be sorted in increasing order of edu_yrs variable.

We can use the sort_values() DataFrame method to sort our dataset. The syntax is as follows:

Sorted_DataFrame = DataFrame.sort_values(by, axis=0, ascending=True)

This returns a sorted copy of the DataFrame.

Parameters:

    by: the column name or list of column names to sort the DataFrame by
    axis: "0" denotes sorting by values in a column. ("1" means sorting by row)
    ascending: if this is "True", sort in ascending order, otherwise descending order

We will sort according to the edu_yrs column: 

In [13]:
df_sorted = adult_income.sort_values(by="edu_yrs", axis=0, ascending=False)

In [14]:
# display the top 5 values (maximum "edu_yrs")
print(df_sorted.head())

       education  edu_yrs     sex  capital_gain  hours_per_week income
75     Doctorate       16    Male             0              40  <=50K
4      Doctorate       16    Male             0              40   >50K
211    Doctorate       16  Female             0              48   >50K
280    Doctorate       16    Male             0              35   >50K
36   Prof-school       15    Male             0              50   >50K


In [15]:
# display the bottom 5 values (minimum "edu_yrs")
print(df_sorted.tail())

    education  edu_yrs     sex  capital_gain  hours_per_week income
87    5th-6th        3    Male             0              35  <=50K
219   1st-4th        2  Female             0              40  <=50K
9     1st-4th        2    Male             0              35  <=50K
38    1st-4th        2    Male             0              40  <=50K
83    1st-4th        2  Female             0              15  <=50K


However, you may notice that even though the data is sorted, multiple rows with the same value for edu_yrs are not arranged in any particular order.

What if we wanted all the rows which have the same value of edu_yrs to be sorted with respect to the hours_per_week column?

We just need to pass the name of the second column we want to sort by, along with the first column as a list to the by parameter:

In [16]:
df_sorted = adult_income.sort_values(by=["edu_yrs","hours_per_week"], axis=0, ascending=False)

# display the top 12 values after sorting
print(df_sorted.head(12))

       education  edu_yrs     sex  capital_gain  hours_per_week income
211    Doctorate       16  Female             0              48   >50K
4      Doctorate       16    Male             0              40   >50K
75     Doctorate       16    Male             0              40  <=50K
280    Doctorate       16    Male             0              35   >50K
26   Prof-school       15    Male             0              50   >50K
36   Prof-school       15    Male             0              50   >50K
80   Prof-school       15    Male         99999              50   >50K
153  Prof-school       15    Male             0              50   >50K
307  Prof-school       15  Female         14084              50   >50K
220      Masters       14  Female         15831              72   >50K
45       Masters       14    Male             0              60   >50K
146      Masters       14  Female          8614              55   >50K


We can even modify this further. It is not necessary that we will want the DataFrame to be sorted in descending order by both the columns.

We might want to get it sorted in descending order of edu_yrs values, while sorting in ascending order of hours_per_week values within that.

To do that, we pass a list to the ascending parameter as well, with the order corresponding to that of the list passed to the by parameter.

For example in our current problem we will pass the following argument ascending = [False, True]

In [17]:
df_sorted = adult_income.sort_values(by=["edu_yrs","hours_per_week"], axis=0, ascending=[False, True])

# display the top 12 values after sorting
print(df_sorted.head(12))

       education  edu_yrs     sex  capital_gain  hours_per_week income
280    Doctorate       16    Male             0              35   >50K
4      Doctorate       16    Male             0              40   >50K
75     Doctorate       16    Male             0              40  <=50K
211    Doctorate       16  Female             0              48   >50K
26   Prof-school       15    Male             0              50   >50K
36   Prof-school       15    Male             0              50   >50K
80   Prof-school       15    Male         99999              50   >50K
153  Prof-school       15    Male             0              50   >50K
307  Prof-school       15  Female         14084              50   >50K
30       Masters       14    Male             0              40   >50K
34       Masters       14    Male             0              40   >50K
91       Masters       14    Male             0              40  <=50K


#### Top Values - nlargest() and nsmallest()

Sometimes we may not be interested in sorting the DataFrame, but just need to look at the top 10 or top 20 instances according to some column/feature.

For example:

    Who are the top 10 earners of capital_gain?
    According to hours_per_week, which 5 people have the lowest working hours?

Instead of sorting and then viewing the top 5 or 10 results, we can use a function to display the largest or smallest n-values according to any column. We will be using the following functions for this: nlargest() and nsmallest()

1. Who are the top 10 earners of "capital-gain"?

In [19]:
df_largest = adult_income.nlargest(10, "capital_gain")

# display results
print(df_largest)

       education  edu_yrs     sex  capital_gain  hours_per_week income
211    Doctorate       16  Female             0              48   >50K
4      Doctorate       16    Male             0              40   >50K
75     Doctorate       16    Male             0              40  <=50K
280    Doctorate       16    Male             0              35   >50K
26   Prof-school       15    Male             0              50   >50K
36   Prof-school       15    Male             0              50   >50K
80   Prof-school       15    Male         99999              50   >50K
153  Prof-school       15    Male             0              50   >50K
307  Prof-school       15  Female         14084              50   >50K
220      Masters       14  Female         15831              72   >50K


2. According to "hours-per-week", which 5 people have the lowest working hours?

In [21]:
# Who are the bottom 5 earners of "capital-gain".
df_smallest = adult_income.nsmallest(5, "capital_gain")

# display results
print(df_smallest)

      education  edu_yrs     sex  capital_gain  hours_per_week income
0  Some-college       10    Male             0              40  <=50K
1  Some-college       10    Male             0              45  <=50K
2       HS-grad        9    Male             0              50   >50K
3       HS-grad        9  Female             0              50  <=50K
4     Doctorate       16    Male             0              40   >50K


we can also pass the list of columns.

In [22]:
# Who are the bottom 5 earners of "capital-gain".
df_smallest = adult_income.nsmallest(5, ["capital_gain", "edu_yrs"])

# display results
print(df_smallest)

    education  edu_yrs     sex  capital_gain  hours_per_week income
9     1st-4th        2    Male             0              35  <=50K
38    1st-4th        2    Male             0              40  <=50K
83    1st-4th        2  Female             0              15  <=50K
219   1st-4th        2  Female             0              40  <=50K
87    5th-6th        3    Male             0              35  <=50K


#### summary



    The pandas DataFrame is a 2D table. It is the Python equivalent of a spreadsheet or SQL table.
    read_csv() function — reads a CSV file and returns a DataFrame
    head() and tail() methods — used to see the first and last few rows
    info() method — prints the datatypes of every variable
    describe() method — summarizes each variable in the DataFrame. For numerical variables, displays the mean, median, etc. For categorical variables, displays the mode, number of unique values, etc.
    sort_values() method — used to sort a DataFrame
        by parameter — for specifying the column to sort by
        ascending parameter — for ascending or descending order
    nlargest(n, column) and nsmallest(n, column) methods — returns the n rows with the largest / smallest values for the specified column

# 0.2 Creating Series and DataFrames

Series which is a 1-dimensional data structure supported by Pandas. In fact, in Pandas, each column of a DataFrame is a Series.

#### series

Just like the DataFrame, Series is another useful data structure provided by the Pandas library.

A Series is a 1-dimensional array. It is capable of holding all data types like integers, strings, floating point numbers, Python objects, etc.

Unlike DataFrames which have an index (row labels) and columns (column labels), Series objects have only one set of labels.

#### Creating a Series

pandas.Series(data=None, index=None)

Here's a description of each of the parameters:

    data — refers to the data to store in the Series. It can be a list, 1D numpy array, dict or a scalar value.
    index — refers to the index labels. If no index is passed, the default index is range 0 to n-1. Index values must be hashable and have the same length as the data.

Additionally, if a dict of key-value pairs is passed as data and no index is passed, then the key is used as the index.

Let us look at some examples of Series construction.

In [23]:
# From a list, without passing any index
s1 = pd.Series([1, 'tom', 32, 'qualified'])
print(s1)

0            1
1          tom
2           32
3    qualified
dtype: object


In [24]:
# From a list, with an index
s2 = pd.Series([1, 'tom', 32, 'qualified'], index=['number', 'name', 'age', 'status'])
print(s2)

number            1
name            tom
age              32
status    qualified
dtype: object


In [25]:
# From a list of integer values, with an index
s3 = pd.Series([1, 345, 14, 24, 12], index=['first', 'second', 'third', 'fourth', 'fifth'])
print(s3)

first       1
second    345
third      14
fourth     24
fifth      12
dtype: int64


In [26]:
# From a dict of key-value pairs
s4 = pd.Series({'number':1, 'name':'tom', 'age':32, 'status':'qualified'})
print(s4)

number            1
name            tom
age              32
status    qualified
dtype: object


the data type ( dtype ) of the Series is inferred from the elements passed to the Series. It is automatically chosen such that all elements in the Series are of same dtype (or a sub-type of dtype). 

#### Creating a DataFrame

pandas.DataFrame(data=None, index=None, columns=None)

Here's a description of each of the parameters:

    data — a 2D array, or a dict (of 1D array, Series, list or dicts).
    index — row index values for the DataFrame that will be created. If not specified, row index values default to the range 0 to n-1 (where n is the number of rows).
    columns — column labels of the DataFrame that will be created. If not specified, column labels default to the range 0 to c-1 (where c is the number of columns).

#### Creating DataFrame from ndarray

we will see how to create a DataFrame using a numpy ndarray as data, and a list of column labels. 

In [28]:
# Create a random 7 x 5 numpy ndarray
np.random.seed(42) # set a seed so that the same random numbers are generated each time
np_array = 10 * np.random.rand(7, 5)

# Create a list of 5 column labels
cols = ['col1', 'col2', 'col3', 'col4', 'col5']

# Create the DataFrame
ndf = pd.DataFrame(data=np_array, columns=cols)

# Display dataframe
print(ndf)

       col1      col2      col3      col4      col5
0  3.745401  9.507143  7.319939  5.986585  1.560186
1  1.559945  0.580836  8.661761  6.011150  7.080726
2  0.205845  9.699099  8.324426  2.123391  1.818250
3  1.834045  3.042422  5.247564  4.319450  2.912291
4  6.118529  1.394939  2.921446  3.663618  4.560700
5  7.851760  1.996738  5.142344  5.924146  0.464504
6  6.075449  1.705241  0.650516  9.488855  9.656320


#### Creating DataFrame from dict

In [29]:
# make three Series'
s1 = pd.Series([10, 20, 30, 40, 50])
s2 = pd.Series(['a', 'b', 'c', 'd', 'e'])
s3 = pd.Series(['one', 'two', 'three', 'four', 'five'])

# create a dict
data_dict = {'col1': s1, 'col2': s2, 'col3': s3}

If we don't pass a list of names to column explicitly, the column labels in the constructed DataFrame will be the ordered list of dict keys.

In [30]:
# create dataframe
df = pd.DataFrame(data=data_dict)

# display dataframe
print(df)

   col1 col2   col3
0    10    a    one
1    20    b    two
2    30    c  three
3    40    d   four
4    50    e   five


If we pass a list to column parameter, then only the dictionary keys which match the list of column labels are selectively kept in the DataFrame.

In [31]:
# data_dict same as defined earlier

# create a list of columns_labes
cols = ['col1', 'col2']

# create DataFrame
df = pd.DataFrame(data=data_dict, columns=cols)

# display DataFrame
print(df)

   col1 col2
0    10    a
1    20    b
2    30    c
3    40    d
4    50    e


#### DataFrame from multiple lists as rows

In [33]:
# create multiple lists (one per row)
a1 = ['one', 1, 'up', 'top', 'beauty']
a2 = ['zero', 0, 'down', 'bottom', 'charm']

# combine the data into a single list
l = [a1, a2]

# create a list of column names
col = ['col1', 'col2', 'col3', 'col4', 'col5']

# create the DataFrame
df2 = pd.DataFrame(data=l, columns=col)

# display DataFrame
print(df2)

   col1  col2  col3    col4    col5
0   one     1    up     top  beauty
1  zero     0  down  bottom   charm


#### Creating or adding rows

DataFrame.append(other, ignore_index=False)

where,

    other - can be a Series or Dictionary. Incase you want to pass multiple rows, you also pass a list of Series, Dictionaries or even a DataFrame.
    ignore_index - if True, it ignores the index of object passed in other and ressigns the row(s) with new index instead. If False (the default value), it preserves the index from other. 

Note: If the columns of DataFrame and other object doesn't match, the additional elements from non existing columns will be filled with NaN. We will avoid doing this for now and assume that the other object we pass has exactly the same columns as the DataFrame.

#### Dict as new row

In [34]:
# declare a key-value pair dict type to match the dimensions of row
row = {'col1':'two', 'col2':2, 'col3':'blue', 'col4':'green', 'col5':'red'}

# pass it to the append() method
new_df = df2.append(row, ignore_index=True)

# display the new DataFrame
print(new_df)

   col1  col2  col3    col4    col5
0   one     1    up     top  beauty
1  zero     0  down  bottom   charm
2   two     2  blue   green     red


#### Series as new row

In [35]:
# create a series with column labels of "df2" as index
row = pd.Series(['three',3,'black','white','grey'],
                index=df2.columns)

# pass it to the append() method
new_df = df2.append(row, ignore_index=True)

# display the new DataFrame
print(new_df)

    col1  col2   col3    col4    col5
0    one     1     up     top  beauty
1   zero     0   down  bottom   charm
2  three     3  black   white    grey


#### Adding multiple rows

In [36]:
# create two series with column labels of "df2" as index
row1 = pd.Series(['four',4,'left','right','center'],
              index=df2.columns)

row2 = pd.Series(['five',5,'Winterfell','Eyrie','Sunspear'],
              index=df2.columns)

# pass it to the append() method
new_df = df2.append([row1, row2], ignore_index=True)

# display the new DataFrame
print(new_df)

   col1  col2        col3    col4      col5
0   one     1          up     top    beauty
1  zero     0        down  bottom     charm
2  four     4        left   right    center
3  five     5  Winterfell   Eyrie  Sunspear


#### Converting a DataFrame to other formats

##### Converting to a ndarray (NumPy array)



    using the Pandas DataFrame .values attribute
    using the Pandas DataFrame .to_numpy() method

 if the DataFrame contains integers and floats, the dtype of the ndarray will be float. But if the DataFrame has numeric as well as non-numeric values, then the dtype will be object.

In [37]:
# print DataFrame
print('The DataFrame')
print(ndf)
print("")

# use the values attribute to return an ndarray
print('Using values attribute')
print(ndf.values)
print("")

The DataFrame
       col1      col2      col3      col4      col5
0  3.745401  9.507143  7.319939  5.986585  1.560186
1  1.559945  0.580836  8.661761  6.011150  7.080726
2  0.205845  9.699099  8.324426  2.123391  1.818250
3  1.834045  3.042422  5.247564  4.319450  2.912291
4  6.118529  1.394939  2.921446  3.663618  4.560700
5  7.851760  1.996738  5.142344  5.924146  0.464504
6  6.075449  1.705241  0.650516  9.488855  9.656320

Using values attribute
[[3.74540119 9.50714306 7.31993942 5.98658484 1.5601864 ]
 [1.5599452  0.58083612 8.66176146 6.01115012 7.08072578]
 [0.20584494 9.69909852 8.32442641 2.12339111 1.81824967]
 [1.8340451  3.04242243 5.24756432 4.31945019 2.9122914 ]
 [6.11852895 1.39493861 2.92144649 3.66361843 4.56069984]
 [7.85175961 1.99673782 5.14234438 5.92414569 0.46450413]
 [6.07544852 1.70524124 0.65051593 9.48885537 9.65632033]]



DataFrame.to_numpy(dtype="")

In this case too, the dtype of the ndarray is chosen such that it can preserve and accommodate all the values from the DataFrame. But with this method we can also explicitly specify the dtype by passing the dtype parameter.

In [38]:
# use the to_numpy() method to convert to ndarray
print('Using to_numpy() method')
print(ndf.to_numpy())
print("")

# use to_numpy() method with explicit dtype
print('Using to_numpy() method with dtype="int"')
print(ndf.to_numpy(dtype='int'))
print("")

Using to_numpy() method
[[3.74540119 9.50714306 7.31993942 5.98658484 1.5601864 ]
 [1.5599452  0.58083612 8.66176146 6.01115012 7.08072578]
 [0.20584494 9.69909852 8.32442641 2.12339111 1.81824967]
 [1.8340451  3.04242243 5.24756432 4.31945019 2.9122914 ]
 [6.11852895 1.39493861 2.92144649 3.66361843 4.56069984]
 [7.85175961 1.99673782 5.14234438 5.92414569 0.46450413]
 [6.07544852 1.70524124 0.65051593 9.48885537 9.65632033]]

Using to_numpy() method with dtype="int"
[[3 9 7 5 1]
 [1 0 8 6 7]
 [0 9 8 2 1]
 [1 3 5 4 2]
 [6 1 2 3 4]
 [7 1 5 5 0]
 [6 1 0 9 9]]



#### Converting to a dict or a list

DataFrame.to_dict(orient='dict')

The orient parameter can take a number of arguments, but we will concentrate on four of them: "dict", "list", "series" and "records".

    For the first three arguments ("dict", "list" and "series" ), the method returns a dict of key-value pairs, where the keys are column labels of the DataFrame. The data-structure of the values are as specified by the orient parameter (dict, list or Series).
        "dict" - this is the default argument. The values of the dict returned are dict themselves with row index as key and elements of the column as values.
        "list" - the values of the dict are lists of corresponding column elements.
        "series" - the values of the dict are Series of column elements, with the row index as index label of the series. The dtype of the series are inferred from the data.
    For the last argument — "records" — the method returns a list with one dict corresponding to each row in the DataFrame.

Let's convert the DataFrame new_df from the "Adding multiple rows" section into these various formats. We'll use Python's pretty print library — pprint — to print the results in a nicely formatted way so that it is easier to look at.

In [39]:
import pprint

# print the actual dataframe
print('The dataframe')
print(new_df)
print('')

print('to_dict() with orient="dict"')
pprint.pprint(new_df.to_dict(orient='dict'))
print('')

print('to_dict() with orient="list"')
pprint.pprint(new_df.to_dict(orient='list'))
print('')

print('to_dict() with orient="series"')
pprint.pprint(new_df.to_dict(orient='series'))
print('')

print('to_dict() with orient="records"')
pprint.pprint(new_df.to_dict(orient='records'))
print('')

The dataframe
   col1  col2        col3    col4      col5
0   one     1          up     top    beauty
1  zero     0        down  bottom     charm
2  four     4        left   right    center
3  five     5  Winterfell   Eyrie  Sunspear

to_dict() with orient="dict"
{'col1': {0: 'one', 1: 'zero', 2: 'four', 3: 'five'},
 'col2': {0: 1, 1: 0, 2: 4, 3: 5},
 'col3': {0: 'up', 1: 'down', 2: 'left', 3: 'Winterfell'},
 'col4': {0: 'top', 1: 'bottom', 2: 'right', 3: 'Eyrie'},
 'col5': {0: 'beauty', 1: 'charm', 2: 'center', 3: 'Sunspear'}}

to_dict() with orient="list"
{'col1': ['one', 'zero', 'four', 'five'],
 'col2': [1, 0, 4, 5],
 'col3': ['up', 'down', 'left', 'Winterfell'],
 'col4': ['top', 'bottom', 'right', 'Eyrie'],
 'col5': ['beauty', 'charm', 'center', 'Sunspear']}

to_dict() with orient="series"
{'col1': 0     one
1    zero
2    four
3    five
Name: col1, dtype: object,
 'col2': 0    1
1    0
2    4
3    5
Name: col2, dtype: int64,
 'col3': 0            up
1          down
2          lef

#### summary


    Series is a 1-dimensional data-structure supported by Pandas.
        Series objects have only one set of labels.
        Each column of a Pandas DataFrame is a Series.
    We can create DataFrames from ndarray, dicts, etc and also convert a DataFrame back to these formats
    We can add rows to a DataFrame using append()

# 0.3 Indexing and Slicing

In [3]:
print(adult_income.head())

      education  edu_yrs     sex  capital_gain  hours_per_week income
0  Some-college       10    Male             0              40  <=50K
1  Some-college       10    Male             0              45  <=50K
2       HS-grad        9    Male             0              50   >50K
3       HS-grad        9  Female             0              50  <=50K
4     Doctorate       16    Male             0              40   >50K


#### Selecting single column using []

selected_col = adult_income["income"]

Note: When we select a column of a Pandas DataFrame this way, the result is the Pandas data-structure called Series. A pandas Series is a 1-dimensional data-structure.

In [5]:
selected_col = adult_income["income"]

# display first few elements
print(selected_col.head())

0    <=50K
1    <=50K
2     >50K
3    <=50K
4     >50K
Name: income, dtype: object


In the output above, there's no column name. That's because we're calling the head() function on a Series. If the result was a dataframe, we would see a column name in the output.

#### Selecting multiple columns using []

In [6]:
# form a list of column labels
cols = ["education", "sex", "hours_per_week", "income"]

# form the subset
subset = adult_income[cols]

# display first few rows
print(subset.head())

      education     sex  hours_per_week income
0  Some-college    Male              40  <=50K
1  Some-college    Male              45  <=50K
2       HS-grad    Male              50   >50K
3       HS-grad  Female              50  <=50K
4     Doctorate    Male              40   >50K


Note that if the list has a single column name, the result is a DataFrame with one-column, which is different from a Series. Let's try it:

In [7]:
cols = ["education"]
subset = adult_income[cols]
print(subset.head())

      education
0  Some-college
1  Some-college
2       HS-grad
3       HS-grad
4     Doctorate


#### Column name as attribute of the DataFrame

In [8]:
selected_col = adult_income.education

# display first few elements
print(selected_col.head())

0    Some-college
1    Some-college
2         HS-grad
3         HS-grad
4       Doctorate
Name: education, dtype: object


#### Selecting subset of rows using []

DataFrame[start:stop]

In [9]:
# subset of DataFrame from row 5 to row 10
print(adult_income[5:11])

       education  edu_yrs     sex  capital_gain  hours_per_week income
5        HS-grad        9    Male             0              20  <=50K
6           11th        7    Male             0              40  <=50K
7        HS-grad        9    Male             0              20  <=50K
8   Some-college       10  Female          8614              39   >50K
9        1st-4th        2    Male             0              35  <=50K
10  Some-college       10    Male             0              40  <=50K


In [10]:
# subset of DataFrame from row 1 to row 5
print(adult_income[:6])

      education  edu_yrs     sex  capital_gain  hours_per_week income
0  Some-college       10    Male             0              40  <=50K
1  Some-college       10    Male             0              45  <=50K
2       HS-grad        9    Male             0              50   >50K
3       HS-grad        9  Female             0              50  <=50K
4     Doctorate       16    Male             0              40   >50K
5       HS-grad        9    Male             0              20  <=50K


In [11]:
# the last row
print(adult_income[-1:])

    education  edu_yrs     sex  capital_gain  hours_per_week income
325       9th        5  Female             0              40  <=50K


Note: adult_income[3] does not work, because Pandas will look for a column with label 3. We must use slices to select rows with [].

To recap, we can use [] in three ways.

    "column_name" — result is a single column as a Series
    ["col1", "col2"] — result is a DataFrame with the list of columns
    start:stop — result is a DataFrame with rows from position start to stop-1

#### Indexing and slicing with iloc

DataFrame.iloc[rows, columns]

The rows and columns parameters in iloc accept three kinds of arguments:

    integer — position of the row / column we want
    list of integers — positions of rows / columns we want
    slice object (start:stop) — range of rows / columns positions we want

##### Selecting by lists / slices with iloc

In [12]:
subset = adult_income.iloc[[0,1,2,5], :]
print(subset)

      education  edu_yrs   sex  capital_gain  hours_per_week income
0  Some-college       10  Male             0              40  <=50K
1  Some-college       10  Male             0              45  <=50K
2       HS-grad        9  Male             0              50   >50K
5       HS-grad        9  Male             0              20  <=50K


In [13]:
subset = adult_income.iloc[:, 0:3]
print(subset.head())

      education  edu_yrs     sex
0  Some-college       10    Male
1  Some-college       10    Male
2       HS-grad        9    Male
3       HS-grad        9  Female
4     Doctorate       16    Male


#### Selecting by single value with iloc

 selecting a single column returns a Series

In [14]:
column = adult_income.iloc[:, 2]
print(column.head())

0      Male
1      Male
2      Male
3    Female
4      Male
Name: sex, dtype: object


Similarly, selecting a single row also returns a Series

In [15]:
row = adult_income.iloc[4, :]
print(row)

education         Doctorate
edu_yrs                  16
sex                    Male
capital_gain              0
hours_per_week           40
income                 >50K
Name: 4, dtype: object


Finally, selecting a single row and a single column just gives the actual data:

In [16]:
value = adult_income.iloc[4, 2]
print(value)

Male


#### Indexing and slicing with loc

DataFrame.loc[rows, columns]

Both rows and columns parameters accept the three argument types that we have discussed so far — a single value, a list of values, and a slice.

The main differences are that:

    The rows and columns parameter take the index labels, and not the positions.
        For rows, so far in the tutorial our row index labels have been the same as position, starting at 0 and going up to n-1. But this will not be true always.
        For columns, the index labels are the column names.
    For slices, both start and stop are included in the subset.

Let's select rows with index labels 10 to 15 (both inclusive), and columns from edu_yrs to hours_per_week (again, both inclusive).

In [17]:
subset = adult_income.loc[10:15, 'edu_yrs':'hours_per_week']
print(subset)

    edu_yrs     sex  capital_gain  hours_per_week
10       10    Male             0              40
11       10  Female             0              60
12        9  Female             0              40
13        9  Female          2202              35
14       10    Male          2202              50
15        9  Female             0              40


In [18]:
subset = adult_income.loc[[2, 4, 6, 8], :]
print(subset)

      education  edu_yrs     sex  capital_gain  hours_per_week income
2       HS-grad        9    Male             0              50   >50K
4     Doctorate       16    Male             0              40   >50K
6          11th        7    Male             0              40  <=50K
8  Some-college       10  Female          8614              39   >50K


In [19]:
df_100 = adult_income.iloc[100:, :]
# display first few rows
print(df_100.head())

        education  edu_yrs     sex  capital_gain  hours_per_week income
100  Some-college       10    Male             0              40   >50K
101       HS-grad        9  Female             0              40  <=50K
102       7th-8th        4    Male             0              40  <=50K
103     Bachelors       13    Male             0              60   >50K
104     Bachelors       13  Female             0              40  <=50K


In [20]:
print('.loc[105:110, :] -- gives rows matching that *index*')
print(df_100.loc[105:110, :])
print('')
print('[105:110] -- (without loc) gives rows from *position* 105 to 110')
print(df_100[105:110])
print('')
print('iloc[105:110, :] -- also gives rows from *position* 105 to 110')
print(df_100.iloc[105:110, :])

.loc[105:110, :] -- gives rows matching that *index*
     education  edu_yrs   sex  capital_gain  hours_per_week income
105  Bachelors       13  Male             0              40   >50K
106       11th        7  Male             0              40  <=50K
107       11th        7  Male             0              36  <=50K
108  Bachelors       13  Male             0              52   >50K
109  Bachelors       13  Male          5178              40   >50K
110       11th        7  Male             0              55  <=50K

[105:110] -- (without loc) gives rows from *position* 105 to 110
        education  edu_yrs     sex  capital_gain  hours_per_week income
205  Some-college       10    Male          5178              40   >50K
206       HS-grad        9  Female             0              32  <=50K
207       HS-grad        9    Male             0              40  <=50K
208       HS-grad        9  Female             0              40  <=50K
209          11th        7  Female             0    

#### Single value with loc

In [22]:
column = adult_income.loc[:, "sex"]
print(column.head())

0      Male
1      Male
2      Male
3    Female
4      Male
Name: sex, dtype: object


Similarly, selecting a single row also returns a Series.

In [23]:
row = adult_income.loc[2, :]
print(row)

education         HS-grad
edu_yrs                 9
sex                  Male
capital_gain            0
hours_per_week         50
income               >50K
Name: 2, dtype: object


In [24]:
print('sex of person at row index 2')
print(adult_income.loc[2, 'sex'])
print('education of person at row index 4')
print(adult_income.loc[4, 'education'])

sex of person at row index 2
Male
education of person at row index 4
Doctorate


#### Chained Indexing

This took place in two steps:

In [25]:
df_100 = adult_income.iloc[100:, :]

print(df_100.iloc[105:110, :])

        education  edu_yrs     sex  capital_gain  hours_per_week income
205  Some-college       10    Male          5178              40   >50K
206       HS-grad        9  Female             0              32  <=50K
207       HS-grad        9    Male             0              40  <=50K
208       HS-grad        9  Female             0              40  <=50K
209          11th        7  Female             0              10  <=50K


one liner

In [26]:
subset = adult_income.iloc[100:, :].iloc[105:110, :]
print(subset)

        education  edu_yrs     sex  capital_gain  hours_per_week income
205  Some-college       10    Male          5178              40   >50K
206       HS-grad        9  Female             0              32  <=50K
207       HS-grad        9    Male             0              40  <=50K
208       HS-grad        9  Female             0              40  <=50K
209          11th        7  Female             0              10  <=50K


Let's see another example of selecting a subset. This time we will select the rows 25 to 30 (by position) and columns income and education. But, we will not use loc or iloc, only the [] which we learnt about at the beginning.

Since [] only takes a single argument, we will use chain indexing to achieve this:

In [27]:
subset = adult_income[25:30][['education', 'income']]
print(subset)

      education income
25      HS-grad  <=50K
26  Prof-school   >50K
27      HS-grad  <=50K
28    Bachelors  <=50K
29    Bachelors  <=50K


Note: Chained indexing is actually a two-step process. Writing things in one line is just convenience, but it's not more computationally efficient for the program. So in the above example, first [25:30] operation selects the rows and creates a temporary DataFrame. Then [['education', 'income']] operation takes place, which selects the columns on the result returned from the first operation.

In [28]:
print('selecting the hours_per_week value from row at position 10')
print(adult_income.iloc[10, :].loc['hours_per_week'])

selecting the hours_per_week value from row at position 10
40


#### summary



    Pandas provides many ways of getting a subset of data from a DataFrame. In this tutorial, we learnt about [], .iloc[,] and .loc[,].
    When using the [] operation
        We can provide a column name or list of column names — DataFrame[column_name] and DataFrame[list of columns labels]
        Or we can provide a slice which selects rows by position — DataFrame[start:stop]
    DataFrame.iloc[rows,columns] — selects a subset of rows and columns by position
    DataFrame.loc[rows,columns] — selects a subset of rows and columns by label
    Both loc and iloc accept three types of parameters — single value, list of values, and slices.
    When we perform two or more indexing operations in a single expression, it is known as chained indexing.
    When selecting columns, it's more natural to select by name. When selecting rows, it's more natural to select by position. 

# 0.4 Criteria Based Selection

#### Selection using Boolean Array (Boolean Indexing)

In [30]:
# create boolean array
b_arr = adult_income["edu_yrs"] >= 12

# print the first 10 values
print(b_arr.head(10))

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8    False
9    False
Name: edu_yrs, dtype: bool


The array created is actually a Pandas Series with elements of datatype bool — so all the values are True or False. 

In [31]:
# selection of subset
temp_df = adult_income[b_arr]

# display first few elements
print(temp_df.head())

      education  edu_yrs     sex  capital_gain  hours_per_week income
4     Doctorate       16    Male             0              40   >50K
16    Bachelors       13    Male             0              40   >50K
22    Bachelors       13  Female             0              40  <=50K
26  Prof-school       15    Male             0              50   >50K
28    Bachelors       13  Female             0              40  <=50K


We can also use loc to perform Boolean Indexing, which works exactly the same way.

In [32]:
temp_df = adult_income.loc[adult_income["edu_yrs"]>=12, :]
print(temp_df.head())

      education  edu_yrs     sex  capital_gain  hours_per_week income
4     Doctorate       16    Male             0              40   >50K
16    Bachelors       13    Male             0              40   >50K
22    Bachelors       13  Female             0              40  <=50K
26  Prof-school       15    Male             0              50   >50K
28    Bachelors       13  Female             0              40  <=50K


#### Criterias using logical operations — and, or, not

In [33]:
# create boolean array
b_arr = (adult_income["edu_yrs"] >= 12) & (adult_income["sex"] == 'Female')

# selection of subset
temp_df = adult_income[b_arr]

# display first few elements
print(temp_df.head())

     education  edu_yrs     sex  capital_gain  hours_per_week income
22   Bachelors       13  Female             0              40  <=50K
28   Bachelors       13  Female             0              40  <=50K
37   Bachelors       13  Female             0              45  <=50K
60   Bachelors       13  Female             0              55   >50K
61  Assoc-acdm       12  Female             0              40  <=50K


In [34]:
# create boolean array
b_arr = (adult_income["capital_gain"] > 1000) | (adult_income["income"] == '>50K')

# selection of subset
temp_df = adult_income[b_arr]

# display first 10 elements
print(temp_df.head(10))

       education  edu_yrs     sex  capital_gain  hours_per_week income
2        HS-grad        9    Male             0              50   >50K
4      Doctorate       16    Male             0              40   >50K
8   Some-college       10  Female          8614              39   >50K
13       HS-grad        9  Female          2202              35  <=50K
14  Some-college       10    Male          2202              50  <=50K
16     Bachelors       13    Male             0              40   >50K
26   Prof-school       15    Male             0              50   >50K
27       HS-grad        9    Male          2463              40  <=50K
30       Masters       14    Male             0              40   >50K
31  Some-college       10    Male          4787              50   >50K


In [35]:
# create boolean array
b_arr = ~(adult_income["education"] == 'Doctorate')

# selection of subset
temp_df = adult_income[b_arr]

# display first 10 elements
print(temp_df.head(10))

       education  edu_yrs     sex  capital_gain  hours_per_week income
0   Some-college       10    Male             0              40  <=50K
1   Some-college       10    Male             0              45  <=50K
2        HS-grad        9    Male             0              50   >50K
3        HS-grad        9  Female             0              50  <=50K
5        HS-grad        9    Male             0              20  <=50K
6           11th        7    Male             0              40  <=50K
7        HS-grad        9    Male             0              20  <=50K
8   Some-college       10  Female          8614              39   >50K
9        1st-4th        2    Male             0              35  <=50K
10  Some-college       10    Male             0              40  <=50K


#### Selection based on datatypes

DataFrame.select_dtypes(include="", exclude="")

Some common valid strings for dtypes are:

    'int' : for integers
    'float' : for floating point numbers
    'bool' : Boolean data type
    'number' : all numeric types
    'categorical' : for pandas dtype categorical
    'object': all object data types, generally strings are the only object datatypes
    'datetime' and 'timedelta': these are datatypes related to time and date. We will learn about these in a later tutorial.

In [36]:
# select numeric dtypes
df_temp = adult_income.select_dtypes(include='number')

# display first few elements
print(df_temp.head())

   edu_yrs  capital_gain  hours_per_week
0       10             0              40
1       10             0              45
2        9             0              50
3        9             0              50
4       16             0              40


#### summary


    With Boolean Indexing, we can select DataFrame rows satisfying some criteria
    We can define criterias / Boolean arrays using comparison operations (using ==, >, etc) and logical operations (using &, | and ~)
    We can also selectively keep columns with particular datatypes using select_dtypes()

# 0.5 Modifying DataFrames

#### Modifying specific values in a DataFrame

In [54]:
adult_income = pd.read_csv("data/adult_income_data_small.csv")

In [38]:
print(adult_income.loc[2, :])

education         HS-grad
edu_yrs                 9
sex                  Male
capital_gain            0
hours_per_week         50
income               >50K
Name: 2, dtype: object


As you can see, the initial value for the element in the row with index 2 and column label education is 'HS-grad'.

Now we will assign it the value 'College':

In [39]:
adult_income.loc[2, 'education'] = 'College'

# print row index 2 to verify modification
print(adult_income.loc[2, :])

education         College
edu_yrs                 9
sex                  Male
capital_gain            0
hours_per_week         50
income               >50K
Name: 2, dtype: object


#### Modifying values based on criteria (Boolean indexing)

In [40]:
print(adult_income.loc[adult_income["edu_yrs"] >= 16, :])

     education  edu_yrs     sex  capital_gain  hours_per_week income
4    Doctorate       16    Male             0              40   >50K
75   Doctorate       16    Male             0              40  <=50K
211  Doctorate       16  Female             0              48   >50K
280  Doctorate       16    Male             0              35   >50K


In [41]:
print(adult_income.head())

      education  edu_yrs     sex  capital_gain  hours_per_week income
0  Some-college       10    Male             0              40  <=50K
1  Some-college       10    Male             0              45  <=50K
2       College        9    Male             0              50   >50K
3       HS-grad        9  Female             0              50  <=50K
4     Doctorate       16    Male             0              40   >50K


Now, we'll select these rows again and modify the education column by assigning it the value 'Ph.D.'.

In [42]:
adult_income.loc[adult_income["edu_yrs"] >= 16, 'education'] = 'Ph.D.'

# Print the rows to verify the modification
print(adult_income.loc[adult_income["edu_yrs"] >= 16, :])
print('')

# Also make sure only the *selected rows* got modified
print(adult_income.head())

    education  edu_yrs     sex  capital_gain  hours_per_week income
4       Ph.D.       16    Male             0              40   >50K
75      Ph.D.       16    Male             0              40  <=50K
211     Ph.D.       16  Female             0              48   >50K
280     Ph.D.       16    Male             0              35   >50K

      education  edu_yrs     sex  capital_gain  hours_per_week income
0  Some-college       10    Male             0              40  <=50K
1  Some-college       10    Male             0              45  <=50K
2       College        9    Male             0              50   >50K
3       HS-grad        9  Female             0              50  <=50K
4         Ph.D.       16    Male             0              40   >50K


#### Modifying columns

##### Modifying column datatype

Before we modify the data itself, let us see how to change the datatype (dtype) of columns in our DataFrame.

Let's start by taking a look at the dtypes of different columns in our DataFrame.

In [43]:
adult_income.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326 entries, 0 to 325
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   education       326 non-null    object
 1   edu_yrs         326 non-null    int64 
 2   sex             326 non-null    object
 3   capital_gain    326 non-null    int64 
 4   hours_per_week  326 non-null    int64 
 5   income          326 non-null    object
dtypes: int64(3), object(3)
memory usage: 15.4+ KB


Although the read_csv() function assigns columns like sex and income as object dtype, for categorical variables a more suitable dtype called category exists in Pandas. Changing to category dtype for these columns saves space, and also allows us to use other helpful functions to find number of unique values, etc. 

DataFrame["column_name"].astype(dtype)

Here the dtype argument specifies the datatype to which we want to convert. This function returns the column with the changed dtype. 

In [50]:
adult_income["income"] = adult_income["income"].astype('category')

# check the datatypes
print("Check the dtypes after converting")
adult_income.info()

Check the dtypes after converting
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326 entries, 0 to 325
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype   
---  ------          --------------  -----   
 0   education       326 non-null    category
 1   edu_yrs         326 non-null    int64   
 2   sex             326 non-null    object  
 3   capital_gain    326 non-null    int64   
 4   hours_per_week  326 non-null    int64   
 5   income          326 non-null    category
 6   hours_per_day   326 non-null    float64 
 7   product         326 non-null    int64   
dtypes: category(2), float64(1), int64(4), object(1)
memory usage: 16.9+ KB


#### Creating new columns / Modifying column values

DataFrame["new_column_name"] = col_values

The col_values can be:

    an integer - the whole column is filled with the same integer,
    an array or a Series - the length should be same as number of rows in the Dataframe

#### Operations on columns

In [45]:
adult_income["hours_per_day"] = adult_income["hours_per_week"] / 5

print(adult_income.head())

      education  edu_yrs     sex  capital_gain  hours_per_week income  \
0  Some-college       10    Male             0              40  <=50K   
1  Some-college       10    Male             0              45  <=50K   
2       College        9    Male             0              50   >50K   
3       HS-grad        9  Female             0              50  <=50K   
4         Ph.D.       16    Male             0              40   >50K   

   hours_per_day  
0            8.0  
1            9.0  
2           10.0  
3           10.0  
4            8.0  


Note that after performing the operations, we don't need to necessarily put the results in the same DataFrame.

For example, in the code below we are just storing the Series as a separate variable. 

In [46]:
hours_per_day = adult_income["hours_per_week"] / 5
print(hours_per_day.head())

0     8.0
1     9.0
2    10.0
3    10.0
4     8.0
Name: hours_per_week, dtype: float64


NumPy functions such as np.exp() or np.log() which work on ndarrays, can also be used with Pandas Series (and DataFrames).

In [47]:
data = np.exp(adult_income["edu_yrs"])
print(data.head())

0    2.202647e+04
1    2.202647e+04
2    8.103084e+03
3    8.103084e+03
4    8.886111e+06
Name: edu_yrs, dtype: float64


#### Operations involving multiple columns

In [48]:
adult_income["product"] = adult_income["hours_per_week"] * adult_income["edu_yrs"]
print(adult_income.head())

      education  edu_yrs     sex  capital_gain  hours_per_week income  \
0  Some-college       10    Male             0              40  <=50K   
1  Some-college       10    Male             0              45  <=50K   
2       College        9    Male             0              50   >50K   
3       HS-grad        9  Female             0              50  <=50K   
4         Ph.D.       16    Male             0              40   >50K   

   hours_per_day  product  
0            8.0      400  
1            9.0      450  
2           10.0      450  
3           10.0      450  
4            8.0      640  


Let's do another example. This time, let's combine two categorical features. Let's say we care about the combination feature (education, income).

In [55]:
adult_income["edu_with_income"] = adult_income["education"]  + "-" + adult_income["income"]
print(adult_income.head())

      education  edu_yrs     sex  capital_gain  hours_per_week income  \
0  Some-college       10    Male             0              40  <=50K   
1  Some-college       10    Male             0              45  <=50K   
2       HS-grad        9    Male             0              50   >50K   
3       HS-grad        9  Female             0              50  <=50K   
4     Doctorate       16    Male             0              40   >50K   

      edu_with_income  
0  Some-college-<=50K  
1  Some-college-<=50K  
2        HS-grad->50K  
3       HS-grad-<=50K  
4      Doctorate->50K  


#### summary


    We can modify subsets of the DataFrame by accessing the element with [], loc or iloc, and then assigning the new value. This includes modifying a single value or a subset of rows and columns.
    We can selectively modify values from DataFrame using Boolean indexing. First we select the rows which match a criterion, and then assign new values to elements.
    We can modify the dtype of a column with astype()
    We can carry out element-wise operations. This includes operations between a column and a scalar, operations between two columns or applying a function element wise to the entire column.
    We can create new columns using the same [] syntax used to select a column.